---
- name: "Gather facts"
  setup:
  when: ansible_os_family is not defined

- block:
    - name: "Including tasks for: [ {{ ansible_os_family }} ]"
      include_tasks: "{{ ansible_os_family }}/main.yml"

  rescue:
    - name: "/!\\ Something went wrong /!\\"
      debug:
      msg: |
        {{ ansible_os_family }} not supported or bug?
          Send me your PR: https://github.com/victorock/ansible-role-rkhunter
